# Generated by Django 2.2.4 on 2019-09-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgProc', '0002_user_cookie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_img', models.ImageField(null=True, upload_to='img/%Y/%m/%d')),
                ('res_img', models.ImageField(null=True, upload_to='img/%Y/%m/%d')),
            ],
        ),
    ]
