# Generated by Django 2.2.4 on 2019-09-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgProc', '0004_record_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='res_img',
            field=models.ImageField(null=True, upload_to='ImgProc/static/img/%Y/%m/%d'),
        ),
    ]
