# Generated by Django 2.2.4 on 2019-09-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgProc', '0007_auto_20190905_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='res_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='src_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
