# Generated by Django 2.2.4 on 2019-09-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgProc', '0009_auto_20190905_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='username',
        ),
        migrations.AlterField(
            model_name='record',
            name='res_img',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d//res/'),
        ),
        migrations.AlterField(
            model_name='record',
            name='src_img',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d//src/'),
        ),
    ]
