# Generated by Django 2.2.4 on 2019-09-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgProc', '0010_auto_20190905_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='res_img',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d/<django.db.models.fields.CharField>/res/'),
        ),
        migrations.AlterField(
            model_name='record',
            name='src_img',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d/<django.db.models.fields.CharField>/src/'),
        ),
    ]
