# Generated by Django 2.2.4 on 2019-09-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgProc', '0011_auto_20190905_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='username',
        ),
        migrations.AlterField(
            model_name='record',
            name='res_img',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d/%H/%M/%S/res/'),
        ),
        migrations.AlterField(
            model_name='record',
            name='src_img',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d/%H/%M/%S/src/'),
        ),
    ]
