# Generated by Django 2.2.4 on 2019-09-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgProc', '0012_auto_20190905_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='time',
            field=models.FloatField(default=0.0),
        ),
    ]
