# Generated by Django 2.2.4 on 2019-09-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgProc', '0013_record_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='t',
            field=models.TimeField(auto_now=True),
        ),
    ]
