# Generated by Django 2.2.4 on 2019-09-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgProc', '0014_record_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
